---
name: docker

"on":
  push:
    paths:
      - 'Dockerfile'
    branches:
      - main
  pull_request:
    paths:
      - 'Dockerfile'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test for docker
        run: npm run test-docker
