---
name: pages

"on":
  push:
    paths-ignore:
      - 'LICENSE'
      - 'README.*'
    branches:
      - main

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Setup dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build