---
name: test

"on":
  push:
    paths-ignore:
      - 'LICENSE'
      - 'README.*'
    branches:
      - main
  pull_request:
    paths-ignore:
      - 'LICENSE'
      - 'README.*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-${{ hashFiles('Dockerfile') }}-${{ hashFiles('package-lock.json') }}
      - name: Build docker image
        run: npm run build-docker
      - name: Install dependencies
        run: npm run docker-run -- ci
        if: steps.cache.outputs.cache-hit != 'true'
      - name: Check code style
        run: npm run docker-run -- run format-check
      - name: Test
        run: npm run docker-run -- run test-coverage
      - name: Build
        run: npm run docker-run -- run build
      - name: Upload test coverage to Codecov
        uses: codecov/codecov-action@v4
