---
name: test

"on":
  push:
    paths-ignore:
      - 'LICENSE'
      - 'README.*'
    branches:
      - main
  pull_request:
    paths-ignore:
      - 'LICENSE'
      - 'README.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Setup dependencies
        run: npm ci
      - name: Check code style
        run: npm run format-check
      - name: Build
        run: npm run build
