---
name: test

"on":
  push:
    paths-ignore:
      - 'LICENSE'
      - 'README.*'
    branches:
      - main
  pull_request:
    paths-ignore:
      - 'LICENSE'
      - 'README.*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
      - name: Setup dependencies
        run: npm ci
      - name: Check code style
        run: npm run format-check
      - name: Test
        run: npm run test-coverage
      - name: Build
        run: npm run build
      - name: Upload test coverage to Codecov
        uses: codecov/codecov-action@v2.1.0
