---
name: test

"on":
  push:
    paths-ignore:
      - 'LICENSE'
      - 'README.*'
    branches:
      - main
  pull_request:
    paths-ignore:
      - 'LICENSE'
      - 'README.*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker image
        run: docker build -t ci .
      - name: Check code style
        run: docker run -t ci npm run format-check
      - name: Test
        run: >-
          docker run
          -v "$PWD/coverage:/app/coverage"
          -t ci
          npm run test-coverage
      - name: Build
        run: docker run -t ci npm run build
      - name: Upload test coverage to Codecov
        uses: codecov/codecov-action@v2.1.0
